-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7hRw0ZIL3+gsafgt
S98r3k/BJSmwX2ouIFKnJabpVlygCgYIKoZIzj0DAQehRANCAATQ8MySnoEucEVB
3kZ7jQmEwTQxCPr929u/+gawIFSbsziLp2eoWlPNkPEGvUUdHGmVaKjjBVRyomLJ
0fOfakGY
-----END PRIVATE KEY-----