#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerformancTEST
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WZMobileContents")]
	public partial class CONTENTSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 확장성 메서드 정의
    partial void OnCreated();
    #endregion
		
		public CONTENTSDataContext() : 
				base(global::PerformancTEST.Properties.Settings.Default.WZMobileContentsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CONTENTSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CONTENTSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CONTENTSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CONTENTSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.USP_BO_GetNoticeDetail")]
		public ISingleResult<USP_BO_GetNoticeDetailResult> USP_BO_GetNoticeDetail([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServiceCode", DbType="Char(6)")] string serviceCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NoticeNo", DbType="Int")] System.Nullable<int> noticeNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), serviceCode, noticeNo);
			return ((ISingleResult<USP_BO_GetNoticeDetailResult>)(result.ReturnValue));
		}
	}
	
	public partial class USP_BO_GetNoticeDetailResult
	{
		
		private string _NoticeType;
		
		private string _NoticeViewType;
		
		private string _PopUpType;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<bool> _IsSticky;
		
		private System.Nullable<byte> _Sort;
		
		private System.Nullable<bool> _IsView;
		
		private System.Nullable<bool> _IsPopUpView;
		
		private string _ReceiveTargetType;
		
		public USP_BO_GetNoticeDetailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeType", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NoticeType
		{
			get
			{
				return this._NoticeType;
			}
			set
			{
				if ((this._NoticeType != value))
				{
					this._NoticeType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoticeViewType", DbType="Char(6) NOT NULL", CanBeNull=false)]
		public string NoticeViewType
		{
			get
			{
				return this._NoticeViewType;
			}
			set
			{
				if ((this._NoticeViewType != value))
				{
					this._NoticeViewType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PopUpType", DbType="Char(6)")]
		public string PopUpType
		{
			get
			{
				return this._PopUpType;
			}
			set
			{
				if ((this._PopUpType != value))
				{
					this._PopUpType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSticky", DbType="Bit")]
		public System.Nullable<bool> IsSticky
		{
			get
			{
				return this._IsSticky;
			}
			set
			{
				if ((this._IsSticky != value))
				{
					this._IsSticky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="TinyInt")]
		public System.Nullable<byte> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this._Sort = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsView", DbType="Bit")]
		public System.Nullable<bool> IsView
		{
			get
			{
				return this._IsView;
			}
			set
			{
				if ((this._IsView != value))
				{
					this._IsView = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPopUpView", DbType="Bit")]
		public System.Nullable<bool> IsPopUpView
		{
			get
			{
				return this._IsPopUpView;
			}
			set
			{
				if ((this._IsPopUpView != value))
				{
					this._IsPopUpView = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiveTargetType", DbType="Char(6)")]
		public string ReceiveTargetType
		{
			get
			{
				return this._ReceiveTargetType;
			}
			set
			{
				if ((this._ReceiveTargetType != value))
				{
					this._ReceiveTargetType = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
